name: Auto Run Colab Every 5 Hours

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Show Python Version
        run: python --version

      - name: Install Chrome & Playwright
        run: |
          sudo apt update
          sudo apt install -y chromium xvfb python3-pip
          pip install --upgrade pip
          pip install playwright nest_asyncio
          playwright install chromium

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Colab Notebook Using Playwright
        run: python run_colab.py
